---
- hosts: all
  gather_facts: False

- hosts: appnode
  remote_user: root

  tasks:
    - name: Download Application Repo
      git:
        repo: 'git@bitbucket.org:JakeCallery/cheevos.git'
        accept_hostkey: yes
        dest: /cheevos
#      key_file: /root/.ssh/id_rsa

    - name: Copy Webserver Keys Direcotry
      copy:
       src: /cheevos/webserver/keys
       dest: /cheevos/webserver

    - name: Copy Webserver Certs
      copy:
        src: /cheevos/certs
        dest: /cheevos

    - name: Install Webpack globally
      npm:
        name: webpack
        global: yes

    - name: Install WebServer Dependencies
      npm:
        path: /cheevos/webserver/src

    - name: Install WebClient Dependencies
      npm:
        path: /cheevos/webclient/src
...